### Get posts
GET http://localhost:3001

### Login with valid credentials
POST http://localhost:3001/uer/login
Content-Type: application/json

{
    "email":"admin@foo.com",
    "password":"admin123"
}

### Login with invalid credentials
POST http://localhost:3001/uer/login
Content-Type: application/json

{
    "email":"admin@foo.com",
    "password":"wrongpassword"
}

### Registration 
POST http://localhost:3001/uer/register
Content-Type: application/json

{
    "email":"test@foo.com",
    "password":"test123"
}